### ISSUE TITLE
NHẮN TIN CHO YẾN NHI NGUYỄN

### ISSUE THREAD

**Issue by vuduydidan** [HaiHardware/QuangHai#1]
địt con mẹ m có facebook con người ta xong đéo nhắn tin, stalk ăn lồn à

**Comment by tienbao08** [comment]
ren'

**Comment by tienbao08** [comment]
https://www.facebook.com/profile.php?id=100017229881779

**Comment by tienbao08** [comment]
real men slide into dm

**Comment by vuduydidan** [comment]
chua fix ma close cai lon ba gia m a

**Comment by tienbao08** [comment]
fix de

**Comment by tienbao08** [comment]
@HaiHardware
